apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carrier-sdk
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["carrier.ocgi.dev"]
  resources: ["gameservers", "gameservers/status"]
  verbs: ["list", "update", "watch", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carrier-sdk
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carrier-sdk-access
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:default:carrier-sdk
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carrier-sdk
